kind: Service
apiVersion: v1
metadata:
  name: crm
  labels:
    app: crm
    app.kubernetes.io/component: crm
    app.kubernetes.io/instance: crm
    app.kubernetes.io/name: crm
    app.kubernetes.io/part-of: crm-app
spec:
  clusterIP: 172.30.78.188
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.78.188
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: crm
    deployment: crm
status:
  loadBalancer: {}
